discord alert reciever

diff --git a/.github/workflows/infra_up.yml b/.github/workflows/infra_up.yml
--- a/.github/workflows/infra_up.yml
+++ b/.github/workflows/infra_up.yml
@@ -147,7 +147,16 @@ jobs:
             echo "ERROR: Grafana credentials missing from Secrets Manager"
             exit 1
           fi
-          envsubst < k8s/eks/monitoring-secrets.yml | kubectl apply -f -
+          envsubst '$GRAFANA_USER $GRAFANA_PASS' < k8s/eks/monitoring-secrets.yml | kubectl apply -f -
+
+          echo "Integrating Discord alerts..."
+          export DISCORD_WEBHOOK=$(echo $SECRET_JSON | jq -r .DISCORD_WEBHOOK)
+
+          if [ -z "$DISCORD_WEBHOOK" ] ]; then
+            echo "ERROR: Discord webhook URL missing from Secrets Manager"
+            exit 1
+          fi
+          envsubst '$DISCORD_WEBHOOK' < k8s/eks/alert-secrets.yml | kubectl apply -f -
 
           echo "Installing kube-prometheus-stack Helm..."
           helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
